
CREATE TABLE usuarios (
    usu_id          int(11) NOT NULL AUTO_INCREMENT,
    usu_nombre      VARCHAR(100),
    usu_usuario     VARCHAR(50),
    usu_password    VARCHAR(255),
    usu_perfil      VARCHAR(50),
    usu_foto        TEXT,
    usu_estado      int(11),
    usu_ultimo_login datetime,
    usu_fecha_create timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    usu_fecha_update datetime,
    usu_fecha_delete datetime,
    PRIMARY KEY (usu_id)
);

INSERT INTO usuarios (usu_id, usu_nombre, usu_usuario, usu_password, usu_perfil, usu_foto, usu_estado, usu_ultimo_login, usu_fecha_create, usu_fecha_update, usu_fecha_delete) VALUES
(1, 'Usuario Administrado', 'admin', '$2a$07$asxx54ahjppf45sd87a5auXBm1Vr2M1NV5t/zNQtGHGpS5fFirrbG', 'Administrador', 'vistas/img/usuarios/admin/994.png', 1, '2024-11-16 16:58:29', '2024-11-16 21:58:30', NULL, NULL),
(2, 'Victor Cotrina', 'vcotrina', '$2a$07$asxx54ahjppf45sd87a5auaK2UuY9I3HoWrDp0X6p.3tlEWlvSpv.', 'Especial', 'vistas/img/usuarios/vcotrina/143.png', 1, '2024-11-17 15:13:44', '2024-11-17 20:13:44', NULL, NULL),
(3, 'Ramiro Cotrina', 'rcotrina', '$2a$07$asxx54ahjppf45sd87a5auSCG6EtWTOSpeybRK.d3z3BAMJt.7teO', 'Vendedor', 'vistas/img/usuarios/rcotrina/410.png', 1, '2024-11-16 17:30:44', '2024-11-16 22:36:47', NULL, NULL);


-- TABLA CENTRO DE COSTO

CREATE TABLE centro_costo (
  cenco_id int(11) NOT NULL AUTO_INCREMENT,
  cenco_codigo text,
  cenco_nombre text,
  cenco_fecha_create timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  cenco_fecha_update datetime DEFAULT NULL,
  cenco_fecha_delete datetime DEFAULT NULL,
  PRIMARY KEY (cenco_id)
);

INSERT INTO centro_costo (cenco_codigo, cenco_nombre) VALUES
('100', 'GERENCIA'),
('200', 'ADMINISTRACIÓN'),
('201', 'CONTABILIDAD'),
('202', 'FINANZAS'),
('300', 'SEGURIDAD'),
('301', 'RECURSOS HUMANOS'),
('400', 'MANTENIMIENTO'),
('500', 'TSE LIMA Y PROVINCIAS - SOLGAS'),
('501', 'CANJE LIMA Y PROVINCIAS - SOLGAS'),
('502', 'TSE HUANCAYO Y PROVINCIAS - SOLGAS'),
('503', 'CANJE HUANCAYO Y PROVINCIAS - SOLGAS'),
('504', 'TSG LIMA Y PROVINCIAS - REPSOL'),
('505', 'TAG PISCO-CALLAO - LIMA GAS'),
('506', 'TTP LIMA - CEMEX'),
('507', 'TSG LIMA Y PROVINCIAS - SOLGAS'),
('508', 'PACKAGED - LIMA - LINDE'),
('509', 'TSG LIMA Y PROVINCIAS - LIMA GAS'),
('510', 'TPG PROVINCIAS - SOLGAS'),
('511', 'TSG LIMA - PRIMAX'),
('600', 'SERVICIO TRANSPORTE VARIOS'),
('601', 'COSTO POR DISTRIBUIR');


-- TABLA EMPRESAS

CREATE TABLE empresas (
  empre_id int(11) NOT NULL AUTO_INCREMENT,
  empre_ruc text  NULL,
  empre_razon_social text  NULL,
  empre_nombre_comercial text  NULL,
  empre_domicilio_legal text  NULL,
  empre_numero_contacto text  NULL,
  empre_email_contacto text  NULL,
  empre_fecha_create  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  empre_fecha_update datetime  NULL ,
  empre_fecha_delete datetime  NULL,
  PRIMARY KEY (empre_id)
); 

INSERT INTO empresas 
(empre_id, empre_ruc, empre_razon_social, empre_nombre_comercial, empre_domicilio_legal, empre_numero_contacto, empre_email_contacto, empre_fecha_create, empre_fecha_update, empre_fecha_delete) 
VALUES 
(1, '20510976887', 'REPARTO PERU S.A.C.', 'REPARTO PERU', 'Av. Manuel de la Torre Nro. 183 (Frente a la Reniec Santa Anita)', '99999999', 'sistemas@repartoperu.com', '2024-03-15 18:05:49', NULL, NULL);

-- TABLA VEHÍCULOS
CREATE TABLE vehiculos (
    vehic_id int(11) NOT NULL AUTO_INCREMENT,    
    vehic_cenco_id int(11),
    vehic_placa VARCHAR(10) UNIQUE NOT NULL,
    vehic_marca VARCHAR(50) NOT NULL,
    vehic_modelo VARCHAR(50) NOT NULL,
    vehic_anio VARCHAR(10) NOT NULL,
    vehic_clase VARCHAR(50) NOT NULL,
    vehic_tipo VARCHAR(50) NOT NULL,
    vehic_numero_vin VARCHAR(50) UNIQUE NOT NULL,
    vehic_numero_motor VARCHAR(50) UNIQUE NOT NULL,
    vehic_jefe_operacion VARCHAR(50) NOT NULL,
    vehic_estado VARCHAR(50) NOT NULL,
    vehic_propietario VARCHAR(100) NOT NULL,
    vehic_fecha_create  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    vehic_fecha_update datetime  NULL ,
    vehic_fecha_delete datetime  NULL,
    PRIMARY KEY (vehic_id),     
    FOREIGN KEY (vehic_cenco_id) REFERENCES centro_costo(cenco_id) ON DELETE CASCADE
);

INSERT INTO vehiculos (
    vehic_cenco_id, 
    vehic_placa, 
    vehic_marca, 
    vehic_modelo, 
    vehic_anio, 
    vehic_clase, 
    vehic_numero_vin, 
    vehic_numero_motor, 
    vehic_jefe_operacion, 
    vehic_estado, 
    vehic_propietario, 
    vehic_fecha_update, 
    vehic_fecha_delete
) VALUES
(2, 'ABC123', 'Toyota', 'Corolla', '2020', 'Sedán', '1HGCM82633A123456', 'NM12345XYZ', 'Juan Pérez', 'Activo', 'Luis Rodríguez', '2025-02-08 14:30:00', NULL),
(2, 'XYZ789', 'Honda', 'Civic', '2019', 'Sedán', '1HGCM82633A654321', 'NM98765ABC', 'María López', 'Activo', 'Pedro Sánchez', '2025-02-08 14:35:00', NULL),
(3, 'JKL456', 'Ford', 'Ranger', '2022', 'Camioneta', '1FTFW1EF2FKD12345', 'NM54321DEF', 'Carlos Gómez', 'Inactivo', 'Ana Fernández', '2025-02-08 15:00:00', '2025-02-01 10:00:00');


CREATE TABLE documentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vehiculo_id INT NOT NULL,
    rev_tec_matpel DATE,
    rev_tec_mg DATE,
    soat DATE NOT NULL,
    tuc DATE NOT NULL,
    tuce_matpel DATE NOT NULL,
    num_rd_vigente VARCHAR(50),
    vencimiento DATE NOT NULL,
    vcto_bonif_neum DATE,
    FOREIGN KEY (vehiculo_id) REFERENCES vehiculos(id) ON DELETE CASCADE
);


CREATE TABLE opts (
  opt_id int(11) NOT NULL AUTO_INCREMENT,
  opt_cenco_codigo text,
  opt_vehiculo_id int(11) ,
  opt_cliente text ,
  opt_lugar text ,
  opt_fecha date NOT NULL,
  opt_observado text ,
  opt_observador text ,
  opt_bps_encontrada text ,
  opt_500_pregunta1 text ,
  opt_500_pregunta2 text ,
  opt_500_pregunta3 text ,
  opt_500_pregunta4 text ,
  opt_500_pregunta5 text ,
  opt_500_pregunta6 text ,
  opt_500_pregunta7 text ,
  opt_500_pregunta8 text ,
  opt_500_pregunta9 text ,
  opt_500_pregunta10 text ,
  opt_500_pregunta11 text ,
  opt_500_pregunta12 text ,
  opt_500_pregunta13 text ,
  opt_500_pregunta14 text ,
  opt_500_pregunta15 text ,
  opt_500_otros text ,
  opt_501_pregunta1 text ,
  opt_501_pregunta2 text ,
  opt_501_pregunta3 text ,
  opt_501_pregunta4 text ,
  opt_501_pregunta5 text ,
  opt_501_pregunta6 text ,
  opt_501_pregunta7 text ,
  opt_501_pregunta8 text ,
  opt_501_pregunta9 text ,
  opt_501_pregunta10 text ,
  opt_501_pregunta11 text ,
  opt_501_pregunta12 text ,
  opt_501_pregunta13 text ,
  opt_501_pregunta14 text ,
  opt_501_otros text ,
  opt_504_pregunta1 text ,
  opt_504_pregunta2 text ,
  opt_504_pregunta3 text ,
  opt_504_pregunta4 text ,
  opt_504_pregunta5 text ,
  opt_504_pregunta6 text ,
  opt_504_pregunta7 text ,
  opt_504_pregunta8 text ,
  opt_504_pregunta9 text ,
  opt_504_pregunta10 text ,
  opt_504_pregunta11 text ,
  opt_504_pregunta12 text ,
  opt_504_pregunta13 text ,
  opt_504_pregunta14 text ,
  opt_504_pregunta15 text ,
  opt_504_pregunta16 text ,
  opt_504_pregunta17 text ,
  opt_504_pregunta18 text ,
  opt_504_pregunta19 text ,
  opt_504_pregunta20 text ,
  opt_504_pregunta21 text ,
  opt_504_pregunta22 text ,
  opt_504_pregunta23 text ,
  opt_504_pregunta24 text ,
  opt_504_pregunta25 text ,
  opt_504_otros text ,
  opt_506_pregunta1 text ,
  opt_506_pregunta2 text ,
  opt_506_pregunta3 text ,
  opt_506_pregunta4 text ,
  opt_506_pregunta5 text ,
  opt_506_pregunta6 text ,
  opt_506_pregunta7 text ,
  opt_506_pregunta8 text ,
  opt_506_pregunta9 text ,
  opt_506_pregunta10 text ,
  opt_506_pregunta11 text ,
  opt_506_pregunta12 text ,
  opt_506_pregunta13 text ,
  opt_506_otros text ,
  opt_507_pregunta1 text ,
  opt_507_pregunta2 text ,
  opt_507_pregunta3 text ,
  opt_507_pregunta4 text ,
  opt_507_pregunta5 text ,
  opt_507_pregunta6 text ,
  opt_507_pregunta7 text ,
  opt_507_pregunta8 text ,
  opt_507_pregunta9 text ,
  opt_507_pregunta10 text ,
  opt_507_pregunta11 text ,
  opt_507_pregunta12 text ,
  opt_507_pregunta13 text ,
  opt_507_pregunta14 text ,
  opt_507_pregunta15 text ,
  opt_507_pregunta16 text ,
  opt_507_pregunta17 text ,
  opt_507_pregunta18 text ,
  opt_507_pregunta19 text ,
  opt_507_pregunta20 text ,
  opt_507_pregunta21 text ,
  opt_507_pregunta22 text ,
  opt_507_pregunta23 text ,
  opt_507_pregunta24 text ,
  opt_507_pregunta25 text ,
  opt_507_otros text ,
  opt_508_pregunta1 text ,
  opt_508_pregunta2 text ,
  opt_508_pregunta3 text ,
  opt_508_pregunta4 text ,
  opt_508_pregunta5 text ,
  opt_508_pregunta6 text ,
  opt_508_pregunta7 text ,
  opt_508_pregunta8 text ,
  opt_508_pregunta9 text ,
  opt_508_pregunta10 text ,
  opt_508_pregunta11 text ,
  opt_508_pregunta12 text ,
  opt_508_pregunta13 text ,
  opt_508_otros text ,
  opt_509_pregunta1 text ,
  opt_509_pregunta2 text ,
  opt_509_pregunta3 text ,
  opt_509_pregunta4 text ,
  opt_509_pregunta5 text ,
  opt_509_pregunta6 text ,
  opt_509_pregunta7 text ,
  opt_509_pregunta8 text ,
  opt_509_pregunta9 text ,
  opt_509_pregunta10 text ,
  opt_509_pregunta11 text ,
  opt_509_pregunta12 text ,
  opt_509_pregunta13 text ,
  opt_509_pregunta14 text ,
  opt_509_pregunta15 text ,
  opt_509_pregunta16 text ,
  opt_509_pregunta17 text ,
  opt_509_pregunta18 text ,
  opt_509_pregunta19 text ,
  opt_509_pregunta20 text ,
  opt_509_pregunta21 text ,
  opt_509_pregunta22 text ,
  opt_509_pregunta23 text ,
  opt_509_pregunta24 text ,
  opt_509_pregunta25 text ,
  opt_509_otros text ,
  opt_511_pregunta1 text ,
  opt_511_pregunta2 text ,
  opt_511_pregunta3 text ,
  opt_511_pregunta4 text ,
  opt_511_pregunta5 text ,
  opt_511_pregunta6 text ,
  opt_511_pregunta7 text ,
  opt_511_pregunta8 text ,
  opt_511_pregunta9 text ,
  opt_511_pregunta10 text ,
  opt_511_pregunta11 text ,
  opt_511_pregunta12 text ,
  opt_511_pregunta13 text ,
  opt_511_pregunta14 text ,
  opt_511_pregunta15 text ,
  opt_511_pregunta16 text ,
  opt_511_pregunta17 text ,
  opt_511_pregunta18 text ,
  opt_511_pregunta19 text ,
  opt_511_pregunta20 text ,
  opt_511_pregunta21 text ,
  opt_511_pregunta22 text ,
  opt_511_pregunta23 text ,
  opt_511_pregunta24 text ,
  opt_511_pregunta25 text ,
  opt_511_otros text , 
  opt_tipo_hallazgo text ,
  opt_relacionado text ,
  opt_decripcion_observacion text ,
  opt_decripcion_adicional text ,
  opt_correccion text ,
  opt_evidencia1 text ,
  opt_evidencia2 text ,
  opt_id_usuario int(11) NOT NULL,
  opt_fecha_create timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  opt_fecha_update datetime DEFAULT NULL,
  opt_fecha_delete datetime DEFAULT NULL,
    PRIMARY KEY (opt_id), 
    FOREIGN KEY (opt_vehiculo_id) REFERENCES vehiculos(vehic_id) ON DELETE CASCADE
); 

CREATE TABLE areas (
  are_id int(11) NOT NULL AUTO_INCREMENT,
  are_nombre VARCHAR(200) NULL,
  are_fecha_create timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  are_fecha_update datetime DEFAULT NULL,
  are_fecha_delete datetime DEFAULT NULL,
  PRIMARY KEY (are_id)
);

CREATE TABLE cargos (
  car_id int(11) NOT NULL AUTO_INCREMENT,
  car_nombre VARCHAR(200) NULL,
  car_fecha_create timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  car_fecha_update datetime DEFAULT NULL,
  car_fecha_delete datetime DEFAULT NULL,
  PRIMARY KEY (car_id)
); 

CREATE TABLE empleados (
  emple_id int(11) NOT NULL AUTO_INCREMENT,
  emple_codigo VARCHAR(50) UNIQUE NOT NULL,
  emple_tipo_documento VARCHAR(100) NULL,
  emple_numero_documento VARCHAR(50) NULL,
  emple_apellido_paterno VARCHAR(100) NULL,
  emple_apellido_materno VARCHAR(100) NULL,
  emple_nombres VARCHAR(100) NULL ,
  emple_fecha_nacimiento date  NULL,  
  emple_nacionalidad VARCHAR(100) NULL ,
  emple_sexo VARCHAR(10) NULL ,
  emple_estado_civil VARCHAR(100) NULL ,
  emple_telefono_movil VARCHAR(100) NULL ,
  emple_telefono_fijo VARCHAR(100) NULL ,
  emple_correo VARCHAR(100) NULL ,
  emple_departamento VARCHAR(100) NULL ,
  emple_provincia VARCHAR(100)  NULL,
  emple_distrito VARCHAR(100) NULL,  
  emple_lugar_residencia VARCHAR(250) NULL ,
  emple_empresa_id int(11) NOT NULL,
  emple_fecha_ingreso date  NULL,
  emple_categoria_ocupacional VARCHAR(100) NULL,  
  emple_cenco_id int(11) NOT NULL,  
  emple_area_id int(11) NOT NULL,
  emple_cargo_id int(11) NOT NULL,
  emple_estado VARCHAR(100) NULL ,
  emple_fecha_cese date  NULL,
  emple_situacion_educativa VARCHAR(100) NULL, 
  emple_estado_educativa VARCHAR(100) NULL, 
  emple_tipo_regimen VARCHAR(100) NULL, 
  emple_tipo_institucion VARCHAR(100) NULL, 
  emple_institucion VARCHAR(200) NULL, 
  emple_carrera VARCHAR(200) NULL, 
  emple_anio VARCHAR(4) NULL, 
  emple_nombre_familiar VARCHAR(100) NULL, 
  emple_telefono_familiar VARCHAR(100) NULL, 
  emple_parentesco VARCHAR(100) NULL, 
  emple_fecha_vencimiento_documento date  NULL,
  emple_archivo_documento VARCHAR(100) NULL ,
  emple_licencia VARCHAR(100) NULL ,
  emple_fecha_vencimiento_a1 date DEFAULT NULL,
  emple_archivo_a1 VARCHAR(100) NULL,
  emple_fecha_vencimiento_a2a date DEFAULT NULL,
  emple_archivo_a2a VARCHAR(100) NULL,
  emple_fecha_vencimiento_a2b date DEFAULT NULL,
  emple_archivo_a2b VARCHAR(100) NULL,
  emple_fecha_vencimiento_a3a date DEFAULT NULL,
  emple_archivo_a3a VARCHAR(100) NULL,
  emple_fecha_vencimiento_a3b date DEFAULT NULL,
  emple_archivo_a3b VARCHAR(100) NULL,
  emple_fecha_vencimiento_a3c date DEFAULT NULL,
  emple_archivo_a3c VARCHAR(100) NULL,
  emple_fecha_vencimiento_b1 date DEFAULT NULL,
  emple_archivo_b1 VARCHAR(100) NULL,
  emple_fecha_vencimiento_b2a date DEFAULT NULL,
  emple_archivo_b2a VARCHAR(100) NULL,
  emple_fecha_vencimiento_b2b date DEFAULT NULL,
  emple_archivo_b2b VARCHAR(100) NULL,
  emple_fecha_vencimiento_b2c date DEFAULT NULL,
  emple_archivo_b2c VARCHAR(100) NULL,
  emple_id_usuario int(11) NOT NULL,
  emple_fecha_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  emple_fecha_update datetime DEFAULT NULL,
  emple_fecha_delete datetime DEFAULT NULL,
  PRIMARY KEY (emple_id),  
  FOREIGN KEY (emple_empresa_id) REFERENCES empresas(empre_id),
  FOREIGN KEY (emple_cenco_id) REFERENCES centro_costo(cenco_id),
  FOREIGN KEY (emple_area_id) REFERENCES areas(are_id),
  FOREIGN KEY (emple_cargo_id) REFERENCES cargos(car_id)
);


CREATE TABLE movimientos (
    movi_id INT AUTO_INCREMENT PRIMARY KEY,
    movi_tipo VARCHAR(10),
    movi_serie VARCHAR(10),
    movi_numero INT,
    movi_moneda VARCHAR(10),
    movi_fecha DATE,
    movi_emple_id INT,
    movi_total DECIMAL(10,2),
    movi_fecha_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    movi_fecha_update datetime DEFAULT NULL,
    movi_fecha_delete datetime DEFAULT NULL,
    FOREIGN KEY (movi_emple_id) REFERENCES empleados(emple_id)
);

CREATE TABLE detalle_movimiento (
    deta_movi_id INT AUTO_INCREMENT PRIMARY KEY,
    deta_movi_movimiento_id INT,
    deta_movi_item INT,
    deta_movi_descripcion VARCHAR(255),
    deta_movi_importe DECIMAL(10,2),
    FOREIGN KEY (deta_movi_movimiento_id) REFERENCES movimientos(movi_id) ON DELETE CASCADE
);

CREATE TABLE config_series (
    conf_seri_id INT AUTO_INCREMENT PRIMARY KEY,
    conf_seri_tipo VARCHAR(10),
    conf_seri_moneda VARCHAR(10),
    conf_seri_serie VARCHAR(10),
    conf_seri_ultimo_numero INT
);




-- 1. Cabecera de la liquidación (lo que arriba dice Nombre, Mes, Día)
CREATE TABLE liquidaciones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo_liq VARCHAR(20) UNIQUE, -- Ej: LIQ-2026-001
    responsable VARCHAR(100),
    dni VARCHAR(15),
    fecha DATE,
    saldo_anterior DECIMAL(10,2),
    total_ingresos DECIMAL(10,2) DEFAULT 0.00,
    total_egresos DECIMAL(10,2) DEFAULT 0.00,
    saldo_final DECIMAL(10,2),
    estado INT DEFAULT 1 -- 1: Abierto, 0: Cerrado
);

-- 2. El detalle (la tabla azul de tu Excel)
CREATE TABLE detalle_gastos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_liquidacion INT,
    tipo_doc VARCHAR(50),
    nro_doc VARCHAR(50),
    razon_social VARCHAR(200),
    concepto TEXT,
    monto DECIMAL(10,2),
    tipo_movimiento ENUM('INGRESO', 'EGRESO'),
    FOREIGN KEY (id_liquidacion) REFERENCES liquidaciones(id) ON DELETE CASCADE
);




